name: Build Golden Image

on:
  push:
    branches:
      - main

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install -y packer

    - name: Configure Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install azure plugin for packer
      run: packer plugins install github.com/hashicorp/azure

    - name: Build Golden Image
      run: packer build azure-image.pkr.hcl
      env:
        RESOURCE_GROUP: "${{ env.RESOURCE_GROUP }}"
